### ISSUE TITLE
Failed to load model class 'AnyModel' from module 'anywidget'

### ISSUE THREAD

**Issue by pkerpedjiev** [higlass/higlass-python#133]
Running into this error when trying to create a Jupyter higlass view. Only seems to happen in Jupyter lab. The code I'm using loads perfectly fine in Jupyter notebook.

Any ideas what could be causing it?

```
[Open Browser Console for more detailed log - Double click to close this message]

Failed to load model class 'AnyModel' from module 'anywidget'

Error: No version of module anywidget is registered
    at f.loadClass (http://localhost:8889/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.b4eddbb09f5fd50a4007.js?v=b4eddbb09f5fd50a4007:1:74934)
    at f.loadModelClass (http://localhost:8889/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.9f709c2076672b1bfe2b.js?v=9f709c2076672b1bfe2b:1:10729)
    at f._make_model (http://localhost:8889/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.9f709c2076672b1bfe2b.js?v=9f709c2076672b1bfe2b:1:7517)
    at f.new_model (http://localhost:8889/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.9f709c2076672b1bfe2b.js?v=9f709c2076672b1bfe2b:1:5137)
    at f.handle_comm_open (http://localhost:8889/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.9f709c2076672b1bfe2b.js?v=9f709c2076672b1bfe2b:1:3894)
    at _handleCommOpen (http://localhost:8889/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.b4eddbb09f5fd50a4007.js?v=b4eddbb09f5fd50a4007:1:73471)
    at KernelConnection._handleCommOpen (http://localhost:8889/static/lab/jlab_core.23d8e5b84f89c4379db3.js:75023:19)
    at async KernelConnection._handleMessage (http://localhost:8889/static/lab/jlab_core.23d8e5b84f89c4379db3.js:75191:25)
```

I have anywidget installed:

```
Python 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:33:09)
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import anywidget
>>> anywidget.__version__
'0.6.3'
```

**Comment by manzt** [comment]
Widgets must be installed prior to starting Jupyter/JupyterLab server. This kind of error can happen if you `%pip install` or `!pip install` within a running juypter session, or in your environment outside of the server, without restarting the jupyter session (not just the kernel).

Please try restarting the server, or if that fails report back the result of `jupyter labextension list` so I can try to help debug further.

**Comment by gfudenberg** [comment]
I believe that @PSmaruj had a similar issue in python3.8 (which was not resolved) regardless of order of installation (and cleaning etc), but @Yaoyx found that the issue resolved with the above recommendations in python3.9

I notice @pkerpedjiev has python3.8.12, which might be the issue

**Comment by pkerpedjiev** [comment]
Oh wow, switching to Python3.10 resolved the issue. How about that?

Thanks @gfudenberg!

**Comment by pkerpedjiev** [comment]
@manzt Thanks for the suggestions! I'll keep those handy if it happens again.
