### ISSUE TITLE
Re-running a cell leads to server failures

### ISSUE THREAD

**Issue by flekschas** [higlass/higlass-python#6]
I noticed when quickly re-running a cell that contains a `higlass.display` call there's a high chance that the server crashes. This can be solved by repeatedly restarting the kernel until things work again.

I am wondering if there's a way to avoid this kind of hiccup.

Here's an error log I got:

```
Traceback (most recent call last):
  File "/Users/Fritz/miniconda3/envs/hg-jupyter/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/Fritz/miniconda3/envs/hg-jupyter/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Fritz/miniconda3/envs/hg-jupyter/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/Fritz/miniconda3/envs/hg-jupyter/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</Users/Fritz/miniconda3/envs/hg-jupyter/lib/python3.7/site-packages/decorator.py:decorator-gen-124>", line 2, in initialize
  File "/Users/Fritz/miniconda3/envs/hg-jupyter/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/Fritz/miniconda3/envs/hg-jupyter/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 469, in initialize
    self.init_sockets()
  File "/Users/Fritz/miniconda3/envs/hg-jupyter/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 238, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/Users/Fritz/miniconda3/envs/hg-jupyter/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 180, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
[W 16:27:40.915 LabApp] KernelRestarter: restart failed
[W 16:27:40.916 LabApp] Kernel 4695ad53-6f8e-4ced-b640-0b7fe7c90f11 died, removing from map.
[W 16:27:40.916 LabApp] Restarting kernel failed: 4695ad53-6f8e-4ced-b640-0b7fe7c90f11
[E 16:27:40.917 LabApp] Exception restarting kernel
    Traceback (most recent call last):
      File "/Users/Fritz/miniconda3/envs/hg-jupyter/lib/python3.7/site-packages/notebook/services/kernels/handlers.py", line 85, in post
        yield gen.maybe_future(km.restart_kernel(kernel_id))
      File "/Users/Fritz/miniconda3/envs/hg-jupyter/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
    RuntimeError: Restart failed
[E 16:27:40.926 LabApp] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Content-Length": "0",
      "Authorization": "token 670eeed9b4fb9d28e603f172b53e072460b68ca8411930ce",
      "Origin": "http://localhost:8889",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36",
      "Dnt": "1",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8889/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,es;q=0.6",
      "Cookie": "_xsrf=2|65fe7d4a|8c63d75b0b719a747b9b9be00899bd52|1551032390; username-localhost-8888=\"2|1:0|10:1551129853|23:username-localhost-8888|44:YmI0OTlkOTllOGQzNGVlM2JjNmQwNWQ1MjI2MGUwMWM=|0f019cb68d1d532237b1cc23ba093ac581ce882d54a3f50832fcacd4a432cba7\"; username-localhost-8889=\"2|1:0|10:1551130036|23:username-localhost-8889|44:MzlmOTg4YzFkYzZmNDg0NWI1NWExZWEzODY5Njc5YWU=|32f7a71ee7c5cad2ac42242654d52c3297f208db5551dfeb51da71415605dd9e\""
    }
[E 16:27:40.926 LabApp] 500 POST /api/kernels/4695ad53-6f8e-4ced-b640-0b7fe7c90f11/restart?1551130038973 (::1) 21949.78ms referer=http://localhost:8889/lab```

**Comment by flekschas** [comment]
Haven't seen this in a while so closing it now
